### ISSUE TITLE
Uncaught TypeError: $injector.invoke(...).then(...).finally is not a function

### ISSUE THREAD

**Issue by ryvo** [Illniyar/visor#17]
Visor v0.1.2 doesn't work with AngularJS v1.6.4. It fails in method Visor.authenticate at line:

    ['finally'](function () {

Console log:

	bundle.c3eb2f5….js:28906 Uncaught TypeError: $injector.invoke(...).then(...).finally is not a function
	    at Object.authenticate (bundle.c3eb2f5….js:28906)
	    at bundle.c3eb2f5….js:28989
	    at Object.invoke (bundle.c3eb2f5….js:34488)
	    at bundle.c3eb2f5….js:34290
	    at forEach (bundle.c3eb2f5….js:29888)
	    at createInjector (bundle.c3eb2f5….js:34290)
	    at doBootstrap (bundle.c3eb2f5….js:31399)
	    at bootstrap (bundle.c3eb2f5….js:31420)
	    at angularInit (bundle.c3eb2f5….js:31305)
	    at bundle.c3eb2f5….js:62852
	authenticate @ bundle.c3eb2f5….js:28906
	(anonymous) @ bundle.c3eb2f5….js:28989
	invoke @ bundle.c3eb2f5….js:34488
	(anonymous) @ bundle.c3eb2f5….js:34290
	forEach @ bundle.c3eb2f5….js:29888
	createInjector @ bundle.c3eb2f5….js:34290
	doBootstrap @ bundle.c3eb2f5….js:31399
	bootstrap @ bundle.c3eb2f5….js:31420
	angularInit @ bundle.c3eb2f5….js:31305
	(anonymous) @ bundle.c3eb2f5….js:62852
	trigger @ bundle.c3eb2f5….js:32916

**Comment by ryvo** [comment]
I need to apologize. The problem was in my ignorance.
